// ChatSystem.idl

module ChatSystem {
    interface ChatControl {
        // Authentification et Inscription
        boolean authentifier(in string pseudo, in string password);
        boolean inscrire(in string pseudo, in string password);

        // Gestion des Salons
        void creerSalon(in string nomSalon, in string utilisateur);
        string rejoindreSalon(in string nomSalon, in string utilisateur);
        void quitterSalon(in string nomSalon, in string utilisateur);
        string listerSalons();

        // Nouvelle méthode pour l'historique
        string getSalonHistory(in string nomSalon);
    };
};